fix: use flac -M when there are more than one available threads

diff --git a/caudec b/caudec
--- a/caudec
+++ b/caudec
@@ -3735,9 +3735,9 @@ encode () {
 				padding=$(( padding + embeddedArtworkBytes ))
 			fi
 			nThreads=$( getNumberOfAvailableThreads "$fileIndex" $Flac_Max_Threads )
-			if [ $nThreads > 2 ]; then mParam='-M'; fi
+			if [ $nThreads > 1 ]; then mParam='-M'; fi
 
-			printf -- "-s`tagline -T`\x00%s" "$wavFile" | xargs -0 flac -j $nThreads $mParam -P $padding $kfm -${compression_FLAC} -o "$encodedFile" 1>/dev/null 2>> "$Self_Errors_File" || exitCode=$Ex_Ko
+			printf -- "-s`tagline -T`\x00%s" "$wavFile" | xargs -0 flac $mParam -j $nThreads -P $padding $kfm -${compression_FLAC} -o "$encodedFile" 1>/dev/null 2>> "$Self_Errors_File" || exitCode=$Ex_Ko
 			if [ $exitCode -eq $Ex_Ok ]; then
 				if [ "$doEmbedUserCoverArt" = 'true' ]; then
 					importArtworkIntoFLAC || exitCode=$Ex_Ko
