feat: don't use preventClipping with ReplayGain

diff --git a/caudec b/caudec
--- a/caudec
+++ b/caudec
@@ -4892,7 +4892,7 @@ computeGainDbfsFromPeak () {
 }
 
 computeTrackGain () {
-	local exitCode=$Ex_Ok file="$1" line nLines=0 decimals trackGain trackPeak albumGain destTagFile clippingPreventionParam=""
+	local exitCode=$Ex_Ok file="$1" line nLines=0 decimals trackGain trackPeak albumGain destTagFile
 	local nThreads fileExtension line rsFile rsLoudness rsGain rsPeak rsPeakDb rsPeakType rsClippingAdjustment
 
 	if [ -e "$file" ]; then
@@ -4916,10 +4916,7 @@ computeTrackGain () {
 
 			*.mp3)
 				mp3rgain -u -s d "$file" 1>/dev/null 2>/dev/null
-				if [ "$preventClipping" = 'true' ]; then
-					clippingPreventionParam="-k"
-				fi
-				line="$( mp3rgain -e --rg2 --tags-only --true-peak $clippingPreventionParam -o 'tsv' -q "$file" 2>> "$Self_Errors_File" | grep -Fv 'MP3 gain' | tr '\t' '|' | tr -d '+' | cut -d '|' -f 3-4 )" ; exitCode=$?
+				line="$( mp3rgain -e --rg2 --tags-only --true-peak -o 'tsv' -q "$file" 2>> "$Self_Errors_File" | grep -Fv 'MP3 gain' | tr '\t' '|' | tr -d '+' | cut -d '|' -f 3-4 )" ; exitCode=$?
 				if [ $exitCode -eq $Ex_Ok -a -n "$line" ]; then
 					trackGain="${line%|*}"
 					trackGain="${trackGain#+*}"
@@ -5258,10 +5255,7 @@ computeM4AGain () {
 		done
 	fi
 
-	if [ "$preventClipping" = 'true' ]; then
-		clippingPreventionParam="-k"
-	fi
-	echo -en "$list" | xargs -0 mp3rgain -a --rg2 --tags-only --true-peak $clippingPreventionParam -o 'tsv' 1> "$analysisFile" 2>> "$Self_Errors_File" ; exitCode=$?
+	echo -en "$list" | xargs -0 mp3rgain -a --rg2 --tags-only --true-peak -o 'tsv' 1> "$analysisFile" 2>> "$Self_Errors_File" ; exitCode=$?
 
 	if [ $exitCode -ne $Ex_Ok ]; then
 		printMessage 'error' 'album_gain' "Album gain"
