fix: opus supports up to 512 kbps

diff --git a/caudec b/caudec
--- a/caudec
+++ b/caudec
@@ -21,7 +21,7 @@
 declare -r Self_Name='caudec'
 declare -r Self_Decode_Name='decaude'
 declare -r Self_Called_As="${0##*/}"
-declare -r Self_Version='3.0.1'
+declare -r Self_Version='3.0.2'
 
 # Ex_Usage: The command was used incorrectly, e.g., with the wrong number of arguments, a bad flag, a bad syntax in a parameter, or whatever.
 # Ex_Data_Err: The input data was incorrect in some way. This should only be used for user's data & not system files.
@@ -783,6 +783,14 @@ getCompressionSetting () {
 			esac
 			;;
 
+		Opus)
+			if [ -z "$value" ]; then value="96"; fi
+			case "$value" in
+				[6-9]|[1-9][0-9]|[1-4][0-9][0-9]|50[0-9]|51[0-2]) compression_Opus="$value" ;;
+				*) printMessage 'error' 'usage' 'bad_value' "$errormsg target bitrate for $codec must be an integer between 6 and 512 in kilobits per second" ; exit $Ex_Usage ;;
+			esac
+			;;
+
 		WavPack|WavPackHybrid|WavPackLossy)
 			if [ -z "$value" ]; then value="gx1"; fi
 			case "$value" in
@@ -830,8 +838,8 @@ getConstantBitrate () {
 		Opus)
 			if [ -z "$bitrate" ]; then bitrate=96; fi # opusenc default
 			case "$bitrate" in
-				[6-9]|[1-9][0-9]|[1-2][0-9][0-9]|3[0-1][0-9]|320) bitrate_Opus="$bitrate" ;;
-				*) printMessage 'error' 'usage' 'bad_value' "$errormsg target bitrate for $codec must be an integer between 6 and 320 in kilobits per second" ; exit $Ex_Usage ;;
+				[6-9]|[1-9][0-9]|[1-4][0-9][0-9]|50[0-9]|51[0-2]) bitrate_Opus="$bitrate" ;;
+				*) printMessage 'error' 'usage' 'bad_value' "$errormsg target bitrate for $codec must be an integer between 6 and 512 in kilobits per second" ; exit $Ex_Usage ;;
 			esac
 			;;
 
@@ -876,8 +884,8 @@ getAverageBitrate () {
 		Opus)
 			if [ -z "$bitrate" ]; then bitrate=96; fi # opusenc default
 			case "$bitrate" in
-				[6-9]|[1-9][0-9]|[1-2][0-9][0-9]|3[0-1][0-9]|320) average_bitrate_Opus="$bitrate" ;;
-				*) printMessage 'error' 'usage' 'bad_value' "$errormsg average bitrate for $codec must be an integer between 6 and 320 in kilobits per second" ; exit $Ex_Usage ;;
+				[6-9]|[1-9][0-9]|[1-4][0-9][0-9]|50[0-9]|51[0-2]) average_bitrate_Opus="$bitrate" ;;
+				*) printMessage 'error' 'usage' 'bad_value' "$errormsg average bitrate for $codec must be an integer between 6 and 512 in kilobits per second" ; exit $Ex_Usage ;;
 			esac
 			;;
 
