fix: remove unnecessary tests, use exit codes where applicable

diff --git a/caudec b/caudec
--- a/caudec
+++ b/caudec
@@ -2665,11 +2665,12 @@ extractFlacArtwork () {
 			return $exitCode
 		fi
 	done
+
 	return $exitCode
 }
 
 extractAPEv2Artwork () {
-	local picNumber=0 picExt='' picType=0 picTypeText='' pattern otherType='' argString='' fieldName=''
+	local exitCode=$Ex_Ok picNumber=0 picExt='' picType=0 picTypeText='' pattern otherType='' argString='' fieldName=''
 
 	for outputCodec in $outputCodecs; do
 		case "$outputCodec" in
@@ -2683,12 +2684,16 @@ extractAPEv2Artwork () {
 			((picType++))
 			((picNumber++))
 		done
-		echo -en "-z${argString}\x00${copyFile}" | xargs -0 APEv2 >/dev/null 2>> "$errorLogFile"
+		if [ -n "$argString" ]; then
+			echo -en "-z${argString}\x00${copyFile}" | xargs -0 APEv2 >/dev/null 2>> "$errorLogFile" || exitCode=$Ex_Ko
+		fi
 	done
+
+	return $exitCode
 }
 
 extractAPEv2Binaries () {
-	local pattern argString='' fieldName='' b=0
+	local exitCode=$Ex_Ok pattern argString='' fieldName='' b=0
 
 	for outputCodec in $outputCodecs; do
 		case "$outputCodec" in
@@ -2704,13 +2709,15 @@ extractAPEv2Binaries () {
 				done < <( APEv2 -z "$copyFile" 2>/dev/null | grep -F '=data:' 2>/dev/null | cut -d '=' -f 1 2>/dev/null )
 
 				if [ -n "$argString" ]; then
-					echo -en "-z${argString}\x00${copyFile}" | xargs -0 APEv2 >/dev/null 2>> "$errorLogFile"
+					echo -en "-z${argString}\x00${copyFile}" | xargs -0 APEv2 >/dev/null 2>> "$errorLogFile" || exitCode=$Ex_Ko
 				fi
 				;;
 
 			*) continue ;;
 		esac
 	done
+
+	return $exitCode
 }
 
 importCoverArt () {
@@ -2756,6 +2763,7 @@ importArtworkIntoFLAC () {
 		fi
 		metaflac --import-picture-from="${picType}||${description}||${f}" "$encodedFile" >/dev/null 2>> "$errorLogFile" || exitCode=$Ex_Ko
 	done
+
 	return $exitCode
 }
 
@@ -2765,13 +2773,13 @@ genOpusArtworkCommandLine () {
 	doEmbedCoverArt="$( shouldEmbedCoverArt "Opus" )"
 	if [ "$doEmbedCoverArt" = "false" ]; then
 		echo "$cmdline"
-		return 0
+		return $Ex_Ok
 	fi
 
 	pattern="x${outputCodec}Y"
 	if [ "$preserveMetadata" = "${preserveMetadata//$pattern/@}" ]; then
 		echo "$cmdline"
-		return 0
+		return $Ex_Ok
 	fi
 
 	importCoverArt || exitCode=$Ex_Ko
@@ -2787,7 +2795,8 @@ genOpusArtworkCommandLine () {
 		cmdline="${cmdline}\x00--picture=${picType}||${description}||${f}"
 	done
 	echo "$cmdline"
-	return 0
+
+	return $exitCode
 }
 
 importArtworkIntoAPEv2 () {
@@ -2913,6 +2922,7 @@ importArtworkIntoMP3 () {
 		fi
 		eyeD3 --quiet --to-v2.4 --add-image="${f}:${picTypeText}:${description}" "$encodedFile" >/dev/null 2>> "$errorLogFile" || exitCode=$Ex_Ko
 	done
+
 	return $exitCode
 }
 
@@ -3129,7 +3139,7 @@ decode () {
 					flac -s -d -o "$wavFile" "$copyFile" >/dev/null 2>> "$errorLogFile" || exitCode=$Ex_Ko
 				fi
 				if [ $exitCode -eq $Ex_Ok ]; then
-					metaflac --no-utf8-convert --export-tags-to="$sourceTagFile" "$copyFile" >/dev/null 2>> "$errorLogFile"  || exitCode=$Ex_Ko
+					metaflac --no-utf8-convert --export-tags-to="$sourceTagFile" "$copyFile" >/dev/null 2>> "$errorLogFile" || exitCode=$Ex_Ko
 					if [ $exitCode -eq $Ex_Ok ]; then
 						extractFlacArtwork || exitCode=$Ex_Ko
 					fi
@@ -3148,8 +3158,7 @@ decode () {
 				wvunpack -q $kfm -m --threads=$nThreads -o "$wavFile" "$copyFile" >/dev/null 2>> "$errorLogFile" || exitCode=$Ex_Ko
 				if [ $exitCode -eq $Ex_Ok ]; then
 					APEv2 -z "$copyFile" 2>> "$errorLogFile" | grep -vE '(=data:)|(=artwork:)' | $sedcmd -e 's@\\n@\n@g' -e 's@\\x00@\x02@g' > "$sourceTagFile" 2>/dev/null
-					extractAPEv2Artwork
-					extractAPEv2Binaries
+					extractAPEv2Artwork && extractAPEv2Binaries
 				fi
 				;;
 
@@ -3159,8 +3168,7 @@ decode () {
 				mac "$copyFile" "$wavFile" -d -threads=$nThreads >/dev/null 2>> "$errorLogFile" || exitCode=$Ex_Ko
 				if [ $exitCode -eq $Ex_Ok ]; then
 					APEv2 -z "$copyFile" 2>> "$errorLogFile" | grep -vE '(=data:)|(=artwork:)' | $sedcmd -e 's@\\n@\n@g' -e 's@\\x00@\x02@g' > "$sourceTagFile" 2>/dev/null
-					extractAPEv2Artwork
-					extractAPEv2Binaries
+					extractAPEv2Artwork && extractAPEv2Binaries
 				fi
 				;;
 
@@ -3763,12 +3771,9 @@ encode () {
 			mac "$wavFile" "$encodedFile" -c${compression_MonkeysAudio}000 -threads=${nThreads} >/dev/null 2>> "$errorLogFile" || exitCode=$Ex_Ko
 			if [ $exitCode -eq $Ex_Ok -a -f "$destTagFile" ]; then
 				if [ $tagCompressionSetting = true ]; then compressionTag="Encoding=$Self_Name $Self_Version / Monkey's Audio $apeVersion / -c${compression_MonkeysAudio}000"; fi
-				printf -- "-R`tagline -t`\x00%s" "$encodedFile" | xargs -0 APEv2 -z >/dev/null 2>> "$errorLogFile" || exitCode=$Ex_Ko
-				if [ $exitCode -eq $Ex_Ok -a "$doEmbedCoverArt" = "true" ]; then
-					importArtworkIntoAPEv2 || exitCode=$Ex_Ko
-				fi
-				if [ $exitCode -eq $Ex_Ok ]; then # FIXME with a -F parameter
-					importBinariesIntoAPEv2 || exitCode=$Ex_Ko
+				printf -- "-R`tagline -t`\x00%s" "$encodedFile" | xargs -0 APEv2 -z >/dev/null 2>> "$errorLogFile"
+				if [ "$doEmbedCoverArt" = "true" ]; then
+					importArtworkIntoAPEv2 && importBinariesIntoAPEv2
 				fi
 			fi
 			;;
@@ -3783,11 +3788,8 @@ encode () {
 				if [ $tagCompressionSetting = true ]; then compressionTag="Encoding=$Self_Name $Self_Version / WavPack $wavpackVersion / -$compression_WavPack"; fi
 				printf -- "-q`tagline -w`\x00%s" "$wavFile" | xargs -0 wavpack --threads=$nThreads -m $kfm -${compression_WavPack} -o "$encodedFile" --no-utf8-convert >/dev/null 2>> "$errorLogFile" || exitCode=$Ex_Ko
 				if [ $exitCode -eq $Ex_Ok -a -f "$destTagFile" ]; then
-					if [ $exitCode -eq $Ex_Ok -a "$doEmbedCoverArt" = "true" ]; then
-						importArtworkIntoAPEv2 || exitCode=$Ex_Ko
-					fi
-					if [ $exitCode -eq $Ex_Ok ]; then # FIXME with a -F parameter
-						importBinariesIntoAPEv2 || exitCode=$Ex_Ko
+					if [ "$doEmbedCoverArt" = "true" ]; then
+						importArtworkIntoAPEv2 && importBinariesIntoAPEv2
 					fi
 				fi
 			fi
@@ -3812,11 +3814,8 @@ encode () {
 			fi
 			printf -- "-q`tagline -w`\x00%s" "$wavFile" | xargs -0 wavpack --threads=$nThreads -m $kfm -o "$encodedFile" -c${compression_WavPack} -b${average_bitrate_WavPackLossy} --no-utf8-convert >/dev/null 2>> "$errorLogFile" || exitCode=$Ex_Ko
 			if [ $exitCode -eq $Ex_Ok -a -f "$destTagFile" ]; then
-				if [ $exitCode -eq $Ex_Ok -a "$doEmbedCoverArt" = "true" ]; then
-					importArtworkIntoAPEv2 || exitCode=$Ex_Ko
-				fi
-				if [ $exitCode -eq $Ex_Ok ]; then # FIXME with a -F parameter
-					importBinariesIntoAPEv2 || exitCode=$Ex_Ko
+				if [ "$doEmbedCoverArt" = "true" ]; then
+					importArtworkIntoAPEv2 && importBinariesIntoAPEv2
 				fi
 			fi
 			;;
@@ -3843,11 +3842,8 @@ encode () {
 				fi
 				printf -- "-q`tagline -w`\x00%s" "$wavFile" | xargs -0 wavpack --threads=$nThreads -m $kfm -o "$encodedFile" -$compression_WavPack -b${average_bitrate_WavPackLossy} --no-utf8-convert >/dev/null 2>> "$errorLogFile" || exitCode=$Ex_Ko
 				if [ $exitCode -eq $Ex_Ok -a -f "$destTagFile" ]; then
-					if [ $exitCode -eq $Ex_Ok -a "$doEmbedCoverArt" = "true" ]; then
-						importArtworkIntoAPEv2 || exitCode=$Ex_Ko
-					fi
-					if [ $exitCode -eq $Ex_Ok ]; then # FIXME with a -F parameter
-						importBinariesIntoAPEv2 || exitCode=$Ex_Ko
+					if [ "$doEmbedCoverArt" = "true" ]; then
+						importArtworkIntoAPEv2 && importBinariesIntoAPEv2
 					fi
 				fi
 			fi
@@ -3887,11 +3883,8 @@ encode () {
 			printf -- "-q`tagline -w`\x00%s" "$namedPipe" | xargs -0 wavpack --threads=$nThreads -m -${compression_WavPack} -o "$encodedFile" --blocksize=512 --merge-blocks --no-utf8-convert >/dev/null 2>> "$errorLogFile" || exitCode=$Ex_Ko
 			rm -f "$namedPipe"
 			if [ $exitCode -eq $Ex_Ok -a -f "$destTagFile" ]; then
-				if [ $exitCode -eq $Ex_Ok -a "$doEmbedCoverArt" = "true" ]; then
-					importArtworkIntoAPEv2 || exitCode=$Ex_Ko
-				fi
-				if [ $exitCode -eq $Ex_Ok ]; then # FIXME with a -F parameter
-					importBinariesIntoAPEv2 || exitCode=$Ex_Ko
+				if [ "$doEmbedCoverArt" = "true" ]; then
+					importArtworkIntoAPEv2 && importBinariesIntoAPEv2
 				fi
 			fi
 			;;
