feat: adjust FLAC and lossyFLAC padding according to the size of all embedded artwork

diff --git a/caudec b/caudec
--- a/caudec
+++ b/caudec
@@ -2886,6 +2886,43 @@ getUserSpecifiedArtworkBytes () {
 	return $exitCode
 }
 
+getFlacEmbeddedArtworkSize () {
+	local exitCode=$Ex_Ok pattern picType picNumber picFile picBasename bytes=0 fileBytes
+
+	pattern="x${outputCodec}Y"
+	if [ "$preserveMetadata" = "${preserveMetadata//$pattern/@}" ]; then
+		echo "$bytes"
+		return $Ex_Ok
+	fi
+
+	bytes="$( getUserSpecifiedArtworkBytes )"
+
+	# "picture-${index}-${picType}-${picNumber}-placeholder.${picExt}"
+	for picFile in "${Self_Swap_Dir}/picture-${index}-"*; do
+		if [ ! -f "$picFile" ]; then # there are no pictures for this file
+			echo "$bytes"
+			return $Ex_Ok
+		fi
+		case "$picFile" in
+			*.txt|*.bin) continue ;;
+		esac
+		if [ ! -r "$picFile" ]; then
+			continue
+		fi
+		if [ $gnustat = true ]; then
+			fileBytes="$( $statcmd -L --printf "%s" "$picFile" 2>/dev/null )"
+		else
+			fileBytes="$( $statcmd -L -n -f "%s" "$picFile" 2>/dev/null )"
+		fi
+		case "$fileBytes" in
+			[0-9]*) bytes=$(( bytes + fileBytes )) ;;
+		esac
+	done
+
+	echo "$bytes"
+	return $exitCode
+}
+
 importCoverArt () {
 	local exitCode=$Ex_Ok userSpecifiedArtwork coverArtType=3 picNumber=0 picExt picFile descFile
 
@@ -3898,7 +3935,7 @@ encode () {
 	local pattern="x${outputCodec}Y" kfm='' statusInfo='' nRunningProcesses listOfOtherFiles
 	local audioFile otherFile otherFileBasename extOtherFile destOtherFile compressionTag='' id3CompressionTag=''
 	local nChannels compressionParam qualityArg coverArtFile='' doEmbedCoverArt="true" bitsPerSample
-	local userCoverArtBytes=0 padding=4096
+	local flacEmbeddedArtworkBytes=0 padding=4096
 	# local doEmbedBinaries="true" # FIXME with a new -F parameter
 
 	getFileProps "$sourceFile" "$outputCodec"
@@ -3950,8 +3987,8 @@ encode () {
 			if [ $keepWavMetadata = true ]; then kfm='--keep-foreign-metadata' ; fi
 			if [ $tagCompressionSetting = true ]; then compressionTag="ENCODING=$Self_Name $Self_Version / FLAC $flacVersion / -$compression_FLAC"; fi
 			if [ "$doEmbedCoverArt" = "true" ]; then
-				userCoverArtBytes="$( getUserSpecifiedArtworkBytes )"
-				padding=$(( padding + userCoverArtBytes ))
+				flacEmbeddedArtworkBytes="$( getFlacEmbeddedArtworkSize )"
+				padding=$(( padding + flacEmbeddedArtworkBytes ))
 			fi
 			nThreads=$( getNumberOfAvailableThreads $index $Flac_Max_Threads )
 			printf -- "-s`tagline -T`\x00%s" "$wavFile" | xargs -0 flac -j $nThreads -P $padding $kfm -${compression_FLAC} -o "$encodedFile" >/dev/null 2>> "$errorLogFile" || exitCode=$Ex_Ko
@@ -4053,6 +4090,10 @@ encode () {
 			destExtension='lossy.flac'; encodedFile="${Self_Swap_Dir}/${index}-${outputCodec}.${destExtension}" destTagFile="${Self_Ctrl_Dir}/${index}.vc.txt"
 			namedPipe="${Self_Swap_Dir}/lossyWAV-pipe-${index}.wav"
 			if [ $tagCompressionSetting = true ]; then compressionTag="ENCODING=$Self_Name $Self_Version / lossyWAV $lossywavVersion / -q $compression_lossyWAV"; fi
+			if [ "$doEmbedCoverArt" = "true" ]; then
+				flacEmbeddedArtworkBytes="$( getFlacEmbeddedArtworkSize )"
+				padding=$(( padding + flacEmbeddedArtworkBytes ))
+			fi
 			# nThreads=$( getNumberOfAvailableThreads $index $Flac_Max_Threads )
 			nThreads=1 # flac -5 -e -p is slower than lossyWAV
 			bitsPerSample="$( soxi -b "$wavFile" 2>/dev/null )"
@@ -4062,7 +4103,7 @@ encode () {
 			else
 				lossywav "$wavFile" -q $compression_lossyWAV -a 6 -s w -A --scale "$lossyWAV_scale" --stdout --silent >/dev/null 2>> "$errorLogFile" > "$namedPipe" &
 			fi
-			printf -- "--totally-silent`tagline -T`\x00%s" "$namedPipe" | xargs -0 flac -j $nThreads -P 4096 -5 -e -p -b 512 -o "$encodedFile" >/dev/null 2>> "$errorLogFile" || exitCode=$Ex_Ko
+			printf -- "--totally-silent`tagline -T`\x00%s" "$namedPipe" | xargs -0 flac -j $nThreads -P $padding -5 -e -p -b 512 -o "$encodedFile" >/dev/null 2>> "$errorLogFile" || exitCode=$Ex_Ko
 			rm -f "$namedPipe"
 			if [ $exitCode -eq $Ex_Ok -a "$doEmbedCoverArt" = "true" ]; then
 				importArtworkIntoFLAC || exitCode=$Ex_Ko
