feat: use -M with FLAC when using multithreading

diff --git a/caudec b/caudec
--- a/caudec
+++ b/caudec
@@ -3671,7 +3671,7 @@ encode () {
 	local audioFile otherFile otherFileBasename extOtherFile destOtherFile
 	local compressionTag='' id3CompressionTag='' m4aCompressionTag=''
 	local nChannels compressionParam qualityArg coverArtFile='' doEmbedUserCoverArt='true' bitsPerSample
-	local embeddedArtworkBytes=0 padding q4param=''
+	local embeddedArtworkBytes=0 padding q4param='' mParam=''
 	# local doEmbedBinaries='true' # FIXME with a new -F parameter
 
 	doEmbedUserCoverArt="$( shouldEmbedUserCoverArt "$outputCodec" )"
@@ -3735,7 +3735,9 @@ encode () {
 				padding=$(( padding + embeddedArtworkBytes ))
 			fi
 			nThreads=$( getNumberOfAvailableThreads "$fileIndex" $Flac_Max_Threads )
-			printf -- "-s`tagline -T`\x00%s" "$wavFile" | xargs -0 flac -j $nThreads -P $padding $kfm -${compression_FLAC} -o "$encodedFile" 1>/dev/null 2>> "$Self_Errors_File" || exitCode=$Ex_Ko
+			if [ $nThreads > 2 ]; then mParam='-M'; fi
+
+			printf -- "-s`tagline -T`\x00%s" "$wavFile" | xargs -0 flac -j $nThreads $mParam -P $padding $kfm -${compression_FLAC} -o "$encodedFile" 1>/dev/null 2>> "$Self_Errors_File" || exitCode=$Ex_Ko
 			if [ $exitCode -eq $Ex_Ok ]; then
 				if [ "$doEmbedUserCoverArt" = 'true' ]; then
 					importArtworkIntoFLAC || exitCode=$Ex_Ko
