fix: R128 opus tags should really contain values that conform to EBU R 128 specs

diff --git a/caudec b/caudec
--- a/caudec
+++ b/caudec
@@ -21,7 +21,7 @@
 declare -r Self_Name='caudec'
 declare -r Self_Decode_Name='decaude'
 declare -r Self_Called_As="${0##*/}"
-declare -r Self_Version='4.4.0'
+declare -r Self_Version='4.4.1'
 
 # Ex_Usage: The command was used incorrectly, e.g., with the wrong number of arguments, a bad flag, a bad syntax in a parameter, or whatever.
 # Ex_Data_Err: The input data was incorrect in some way. This should only be used for user's data & not system files.
@@ -5046,7 +5046,7 @@ computeOpusAlbumGain () {
 			list="${list}\x00${sourceFile}"
 		fi
 	done
-	echo -en "$list" | xargs -0 opusgain -j $nProcesses -a -p rg 1>/dev/null 2>> "$Self_Errors_File" || exitCode=$Ex_Ko
+	echo -en "$list" | xargs -0 opusgain -j $nProcesses -a -p r128 1>/dev/null 2>> "$Self_Errors_File" || exitCode=$Ex_Ko
 	if [ $exitCode -ne $Ex_Ko ]; then
 		# opusgain changes the rights on the files it touches, to u=rw,go=
 		chmod u=rw,go=r "${sourceFiles[@]}" 1>/dev/null 2>> "$Self_Errors_File"
@@ -5056,7 +5056,7 @@ computeOpusAlbumGain () {
 		for sourceFile in "${sourceFiles[@]}"; do
 			trackPlaybackGain="$( opusinfo "$sourceFile" | grep -F "R128_TRACK_GAIN=" | cut -d '=' -f 2 | cut -d ' ' -f 1 )"
 			trackPlaybackGain="${trackPlaybackGain#+*}"
-			trackDecibels="$( echo "scale=3; ($albumPlaybackGain + ($trackPlaybackGain / 256) + 5) / 1" | bc 2>> "$Self_Errors_File" )"
+			trackDecibels="$( echo "scale=3; ($albumPlaybackGain + ($trackPlaybackGain / 256)) / 1" | bc 2>> "$Self_Errors_File" )"
 			trackDecibels="$( printf "%.2f" "$trackDecibels" )"
 			signedTrackGain="$trackDecibels"
 			if [ "${signedTrackGain:0:1}" != '-' -a "${signedTrackGain:0:1}" != '+' ]; then
