wip: rsgain

diff --git a/caudec b/caudec
--- a/caudec
+++ b/caudec
@@ -5283,6 +5283,48 @@ computeAlbumGain () {
 	return $exitCode
 }
 
+computeRsgain () {
+	local exitCode=$Ex_Ok list trackFiles trackFile trackFileIndex=0 albumGain signedAlbumGain
+	local outputCodec milliseconds paddedFileIndex fileIndex destFile basePath
+	local rsFile rsLoudness rsGain rsPeak rsPeakDb rsPeakType rsClippingAdjustment
+
+	trackFiles=()
+	for sourceFile in "${sourceFiles[@]}"; do
+		trackFiles[$trackFileIndex]="$sourceFile"
+		(( trackFileIndex++ ))
+		if [ -z "$list" ]; then
+			list="$sourceFile"
+		else
+			list="${list}\x00${sourceFile}"
+		fi
+	done
+
+	OIFS="$IFS"
+	IFS="$( echo -en "\t" )"
+	read rsFile rsLoudness rsGain rsPeak rsPeakDb rsPeakType rsClippingAdjustment < <( echo -en "$list" | xargs -0 rsgain custom -q -O -a -t -s i -l "$AUDIO_TARGET_LOUDNESS" 2>> "$Self_Errors_File" | grep -E '^Album' )
+	IFS="$OIFS"
+	if [ -n "$rsGain" ]; then
+		# rsgain changes the rights on the files it touches, to u=rw,go=
+		chmod u=rw,go=r "${trackFiles[@]}" 1>/dev/null 2>> "$Self_Errors_File"
+
+		albumGain="${rsGain#+*}"
+		if [ -z "$albumGain" ]; then
+			exitCode=$Ex_Ko
+		fi
+
+		signedAlbumGain="$albumGain"
+		if [ "${albumGain:0:1}" != '-' -a "${albumGain:0:1}" != '+' ]; then
+			albumGain="+${albumGain}"
+		fi
+
+		printMessage 'success' 'album_gain' "${albumGain} dB" "Album gain: $albumGain dB" "path:"
+	else
+		printMessage 'error' 'album_gain' "Album gain"
+	fi
+
+	return $exitCode
+}
+
 # https://github.com/FrancisRussell/zoog
 computeOpusAlbumGain () {
 	local exitCode=$Ex_Ok albumPath="$1" list trackFiles trackFile trackFileIndex=0 albumPlaybackGain trackPlaybackGain
@@ -5970,7 +6012,7 @@ printHumanStats () {
 	seconds="$( printf 'scale=6; %.6f - %.6f\n' "$time2" "$time1" | bc )"
 	if [ "$seconds" = '0' ]; then seconds='1'; fi # prevent division by 0 situations
 
-	while read fileMilliseconds index; do
+	while read fileMilliseconds paddedFileIndex fileIndex; do
 		duration=$(( duration + fileMilliseconds ))
 	done < "${Self_Data_Dir}/millisecondsAndFileIndexes.list"
 
@@ -7312,7 +7354,7 @@ elif [ "$computeReplayGain" = 'true' ]; then
 	else
 		time1="$( $datecmd '+%s' ).0"
 	fi
-	if [ "$allFilesAreOpus" != 'true' ]; then
+	if [ "$allFilesAreOpus" != 'true' -a $nProcesses -ne 1 ]; then
 		for (( processNumber=0; processNumber < nProcesses; processNumber++ )); do
 			computeTrackGains &
 		done
@@ -7382,6 +7424,8 @@ if [ $exitCode -eq $Ex_Ok ]; then
 				if [ "$allFilesAreOpus" = 'true' ]; then
 					processNumber=0
 					computeOpusAlbumGain '' || exitCode=$Ex_Ko
+				elif [ $nProcesses -eq 1 ]; then
+					computeRsgain || exitCode=$Ex_Ko
 				else
 					computeAlbumGain 'any' '' $processNumber || exitCode=$Ex_Ko
 				fi
